HAL resources can declare a custom "MIME Type" (or "Content Type") that clients should use in order to interact with the API. Grails includes two generic HAL MIME types in the default `application.yml`:

[source,yml]
.grails-app/conf/application.yml
----
include::{sourceDir}/grails-app/conf/application.yml[indent=0,lines="28..44"]
----

You can specify a custom MIME type for your API if you wish, by adding an entry to this configuration:

[source,yml]
.grails-app/conf/application.yml
----
include::{sourceDir}/grails-app/conf/application.yml[indent=0,lines="42..55"]
----
<1> Specifies a MIME type called `inventory`, and gives it a type specification (by convention, `vnd` indicates a "vendor" MIME type)

Now you can use this custom MIME type in your JSON views, using the `type` helper method:

[source, groovy]
.grails-app/views/product/show.gson
----
include::{sourceDir}/grails-app/views/product/show_mime.gson[]
----
<1> The `hal.type()` method takes a string to identify the custom MIME type in the `application.yml` file, or an explicit MIME specification as a string

Make a request to `http://localhost:8080/api/products/1` to see the custom content-type:

[source, bash]
----
$ curl -i localhost:8080/product/1

HTTP/1.1 200
X-Application-Context: application:development
Content-Type: application/vnd.com.example.inventory+json;charset=UTF-8 //<1>
Transfer-Encoding: chunked
Date: Sun, 05 Feb 2017 01:51:08 GMT

{
    "_links": {
        "self": {
            "href":"http://localhost:8080/api/products/1",
            "hreflang":"en_US",
            "type":"application/hal+json"
        }
    },
    "_embedded":{
        "category":{
            "_links":{
                "self":{
                    "href":"http://localhost:8080/api/categories/1",
                    "hreflang":"en_US",
                    "type":"application/hal+json"
                }
            },
            "name":"Clothing","version":0
        }
    },
    "id":"CLOTH001",
    "name":"Cargo Pants",
    "price":15.00
}
----
<1> Note the new MIME type in the `Content-Type` header